fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile

accueil:
    pattern:  /
    defaults: { _controller: NIPAUserBundle:Default:index }

user:
    pattern:  /user
    defaults: { _controller: NIPAUserBundle:User:index }

groupe:
    path: groupe/show/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:show }

groupe_add:
    path: groupe/add
    defaults: { _controller: NIPAUserBundle:Groupe:addGroupe }

groupe_edit:
    path: groupe/edit/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:editGroupe }

groupe_add_users:
    path: groupe/edit/addUsers/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:addUsers }

groupe_delete_users:
    path: groupe/edit/{groupeId}/deleteUsers/{identifiant}
    defaults: { _controller: NIPAUserBundle:Groupe:deleteUsers }

administration:
    pattern:  /administration
    defaults: { _controller: NIPAUserBundle:Administration:show }

administration_user_delete:
    path: profile/delete/{identifiant}
    defaults: { _controller: NIPAUserBundle:Administration:deleteUser }

administration_groupe_delete:
    path: groupe/delete/{groupeId}
    defaults: { _controller: NIPAUserBundle:Administration:deleteGroupe }

administration_champ_enveloppe_add:
    path: champ/enveloppe/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:addChampEnveloppe }

administration_champ_enveloppe_edit:
    path: champ/enveloppe/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:editChampEnveloppe }

administration_champ_enveloppe_delete:
    path: champ/enveloppe/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:deleteChampEnveloppe }

administration_champ_annee_add:
    path: champ/annee/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:addChampAnnee }

administration_champ_annee_edit:
    path: champ/annee/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:editChampAnnee }

administration_champ_annee_delete:
    path: champ/annee/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:deleteChampAnnee }

administration_champ_statut_add:
    path: champ/statut/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:addChampStatut }

administration_champ_statut_edit:
    path: champ/statut/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:editChampStatut }

administration_champ_statut_delete:
    path: champ/statut/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsPortefeuille:deleteChampStatut }

administration_demande_champ_direction_add:
    path: champ/direction/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampDirection }

administration_demande_champ_direction_edit:
    path: champ/direction/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampDirection }

administration_demande_champ_direction_delete:
    path: champ/direction/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampDirection }

administration_demande_champ_divers_add:
    path: champ/divers/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampDivers }

administration_demande_champ_divers_edit:
    path: champ/divers/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampDivers }

administration_demande_champ_divers_delete:
    path: champ/divers/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampDivers }

administration_demande_champ_EM_add:
    path: champ/EM/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampEM }

administration_demande_champ_EM_edit:
    path: champ/EM/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampEM }

administration_demande_champ_EM_delete:
    path: champ/EM/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampEM }

administration_demande_champ_instance_add:
    path: champ/instance/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampInstance }

administration_demande_champ_instance_edit:
    path: champ/instance/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampInstance }

administration_demande_champ_instance_delete:
    path: champ/instance/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampInstance }

administration_demande_champ_interlocuteurMOA_add:
    path: champ/interlocuteur/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampInterlocuteurMOA }

administration_demande_champ_interlocuteurMOA_edit:
    path: champ/interlocuteur/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampInterlocuteurMOA }

administration_demande_champ_interlocuteurMOA_delete:
    path: champ/interlocuteur/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampInterlocuteurMOA }

administration_demande_champ_offres_add:
    path: champ/offres/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampOffres }

administration_demande_champ_offres_edit:
    path: champ/offres/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampOffres }

administration_demande_champ_offres_delete:
    path: champ/offres/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampOffres }

administration_demande_champ_PM_add:
    path: champ/PM/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampPM }

administration_demande_champ_PM_edit:
    path: champ/PM/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampPM }

administration_demande_champ_PM_delete:
    path: champ/PM/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampPM }

administration_demande_champ_priorite_add:
    path: champ/priorite/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampPriorite }

administration_demande_champ_priorite_edit:
    path: champ/priorite/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampPriorite }

administration_demande_champ_priorite_delete:
    path: champ/priorite/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampPriorite }

administration_demande_champ_SDM_add:
    path: champ/SDM/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampSDM }

administration_demande_champ_SDM_edit:
    path: champ/SDM/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampSDM }

administration_demande_champ_SDM_delete:
    path: champ/SDM/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampSDM }

administration_demande_champ_demande_statut_add:
    path: champ/demande_statut/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampStatut }

administration_demande_champ_demande_statut_edit:
    path: champ/demande_statut/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampStatut }

administration_demande_champ_demande_statut_delete:
    path: champ/demande_statut/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampStatut }

administration_demande_champ_statut_instance_add:
    path: champ/statut_instance/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampStatutInstance }

administration_demande_champ_statut_instance_edit:
    path: champ/statut_instance/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampStatutInstance }

administration_demande_champ_statut_instance_delete:
    path: champ/statut_instance/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampStatutInstance }

administration_demande_champ_type_projet_add:
    path: champ/type_projet/add
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:addChampTypeProjet }

administration_demande_champ_type_projet_edit:
    path: champ/type_projet/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:editChampTypeProjet }

administration_demande_champ_type_projet_delete:
    path: champ/type_projet/delete
    defaults: { _controller: NIPAUserBundle:AdministrationChampsDemande:deleteChampTypeProjet }

administration_projet_champ_etape_edit:
    path: champ/etape/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsProjet:editChampEtape }

administration_projet_champ_phase_edit:
    path: champ/phase/edit
    defaults: { _controller: NIPAUserBundle:AdministrationChampsProjet:editChampPhase }

administration_projet_champ_phase_edit_ALL:
    path: champ/phase/edit/ALL
    defaults: { _controller: NIPAUserBundle:AdministrationChampsProjet:editChampPhaseALL }

groupe_permission_add:
    path: groupe/permission/add/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:addPermissionGroupe }

groupe_permission_edit:
    path: groupe/permission/edit/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:editPermissionGroupe }