fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile

accueil:
    pattern:  /
    defaults: { _controller: NIPAUserBundle:Default:index }

user:
    pattern:  /user
    defaults: { _controller: NIPAUserBundle:User:index }

groupe:
    path: groupe/show/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:show }

groupe_add:
    path: groupe/add
    defaults: { _controller: NIPAUserBundle:Groupe:addGroupe }

groupe_edit:
    path: groupe/edit/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:editGroupe }

groupe_add_users:
    path: groupe/edit/addUsers/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:addUsers }

groupe_delete_users:
    path: groupe/edit/{groupeId}/deleteUsers/{identifiant}
    defaults: { _controller: NIPAUserBundle:Groupe:deleteUsers }

administration:
    pattern:  /administration
    defaults: { _controller: NIPAUserBundle:Administration:show }

administration_user_delete:
    path: profile/delete/{identifiant}
    defaults: { _controller: NIPAUserBundle:Administration:deleteUser }

administration_groupe_delete:
    path: groupe/delete/{groupeId}
    defaults: { _controller: NIPAUserBundle:Administration:deleteGroupe }

administration_champ_enveloppe_add:
    path: champ/enveloppe/add
    defaults: { _controller: NIPAUserBundle:Administration:addChampEnveloppe }

administration_champ_enveloppe_edit:
    path: champ/enveloppe/edit
    defaults: { _controller: NIPAUserBundle:Administration:editChampEnveloppe }

administration_champ_enveloppe_delete:
    path: champ/enveloppe/delete
    defaults: { _controller: NIPAUserBundle:Administration:deleteChampEnveloppe }

administration_champ_annee_add:
    path: champ/annee/add
    defaults: { _controller: NIPAUserBundle:Administration:addChampAnnee }

administration_champ_annee_edit:
    path: champ/annee/edit
    defaults: { _controller: NIPAUserBundle:Administration:editChampAnnee }

administration_champ_annee_delete:
    path: champ/annee/delete
    defaults: { _controller: NIPAUserBundle:Administration:deleteChampAnnee }

administration_champ_statut_add:
    path: champ/statut/add
    defaults: { _controller: NIPAUserBundle:Administration:addChampStatut }

administration_champ_statut_edit:
    path: champ/statut/edit
    defaults: { _controller: NIPAUserBundle:Administration:editChampStatut }

administration_champ_statut_delete:
    path: champ/statut/delete
    defaults: { _controller: NIPAUserBundle:Administration:deleteChampStatut }

groupe_permission_add:
    path: groupe/permission/add/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:addPermissionGroupe }

groupe_permission_edit:
    path: groupe/permission/edit/{groupeId}
    defaults: { _controller: NIPAUserBundle:Groupe:editPermissionGroupe }