<?php

namespace NIPA\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    // Méthode avec createQuery de entity manager
    public function getLastPosted($limit = 5)
    {
        return $this->_em->createQuery('
            SELECT
                d
            FROM
                NIPAFirstMyBundle:Utilisateur d
            ORDER BY
                d.Nom DESC
        ')
        ->setMaxResults($limit);
        //->setParameter('enabled', true);
    }
    
    // Méthode avec QueryBuilder de Doctrine
    public function getLastPosted2($limit = 5)
    {
        return $this->createQueryBuilder('d')
        //->where('d.isEnabled = :enabled')
        //->setParameter('enabled', true)
        ->addOrderBy('d.updatedAt', "DESC")
        ->addOrderBy('d.id', "DESC")
        ->setMaxResults($limit);
    }
    
}