portefeuille:
    path:     /portefeuille
    defaults: { _controller: NIPAProjetBundle:Portefeuille:index }

portefeuille_new:
    path:     /portefeuille/new
    defaults: { _controller: NIPAProjetBundle:Portefeuille:addPortefeuille }

portefeuille_budget_prev:
    path:     /portefeuille/EditBudgetPrev/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editBudgetPrev }

portefeuille_budget_prev_delete:
    path:     /portefeuille/DeleteBudgetPrev/{id}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:deleteBudgetPrev }

portefeuille_budget_cons:
    path:     /portefeuille/budgetCons/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editBudgetCons }

portefeuille_edit:
    path:     /portefeuille/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editPortefeuille }

portefeuille_delete:
    path:     /portefeuille/delete/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:deletePortefeuille }

projet:
    path:     /projet
    defaults: { _controller: NIPAProjetBundle:Projet:index }

demande:
    path:     /demande
    defaults: { _controller: NIPAProjetBundle:Demande:index }

demande_new:
    path:     /demande/new
    defaults: { _controller: NIPAProjetBundle:Demande:addDemande }

demande_edit:
    path:     /demande/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Demande:editDemande }

demande_add_portefeuilles:
    path: demande/edit/addPortfeuilles/{reference}
    defaults: { _controller: NIPAProjetBundle:Demande:addPortefeuilles }

demande_delete_portefeuilles:
    path: demande/edit/{referenceDemande}/deletePortefeuilles/{referencePortefeuille}
    defaults: { _controller: NIPAProjetBundle:Demande:deletePortefeuilles }

demande_update_budget:
    path: demande/edit/{reference}/budget/update
    defaults: { _controller: NIPAProjetBundle:Demande:editBudget }

demande_delete_budget:
    path: demande/edit/{reference}/budget/delete
    defaults: { _controller: NIPAProjetBundle:Demande:deleteBudget }

demande_add_instance:
    path: demande/edit/{reference}/instance/add
    defaults: { _controller: NIPAProjetBundle:Demande:addInstance }

demande_delete_instance:
    path: demande/edit/{reference}/instance/delete
    defaults: { _controller: NIPAProjetBundle:Demande:deleteInstance }

demande_delete:
    path: demande/delete/{reference}
    defaults: { _controller: NIPAProjetBundle:Demande:deleteDemande }

update_filtres:
    path: demande/filtres/update
    defaults: { _controller: NIPAProjetBundle:Demande:filtres }

projet_new:
    path: projet/new
    defaults: { _controller: NIPAProjetBundle:Projet:addProjet }

projet_edit:
    path: projet/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:editProjet }

projet_delete:
    path: projet/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:deleteProjet }

projet_load_demande:
    path: projet/load/demande
    defaults: { _controller: NIPAProjetBundle:Projet:loadProjetDemande }

projet_maj_en_realisation:
    path: projet/update/enRealisation/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:updateEnRealisation }

projet_maj_en_conception:
    path: projet/update/enConception/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:updateEnConception }

projet_maj_en_cadrage:
    path: projet/update/enCadrage/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:updateEnCadrage }

update_projet_instance:
    path: projet/update/instance/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:updateInstanceProjet }

delete_projet_instance:
    path: projet/delete/instance/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:deleteInstanceProjet }

add_projet_budget:
    path: projet/add/budget/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:addBudgetProjet }

delete_projet_budget:
    path: projet/delete/budget/{reference}
    defaults: { _controller: NIPAProjetBundle:Projet:deleteBudgetProjet }