portefeuille:
    path:     /portefeuille
    defaults: { _controller: NIPAProjetBundle:Portefeuille:index }

portefeuille_new:
    path:     /portefeuille/new
    defaults: { _controller: NIPAProjetBundle:Portefeuille:addPortefeuille }

portefeuille_budget_prev:
    path:     /portefeuille/EditBudgetPrev/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editBudgetPrev }

portefeuille_budget_prev_delete:
    path:     /portefeuille/DeleteBudgetPrev/{id}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:deleteBudgetPrev }

portefeuille_budget_cons:
    path:     /portefeuille/budgetCons/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editBudgetCons }

portefeuille_edit:
    path:     /portefeuille/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:editPortefeuille }

portefeuille_delete:
    path:     /portefeuille/delete/{reference}
    defaults: { _controller: NIPAProjetBundle:Portefeuille:deletePortefeuille }

projet:
    path:     /projet
    defaults: { _controller: NIPAProjetBundle:Projet:index }

demande:
    path:     /demande
    defaults: { _controller: NIPAProjetBundle:Demande:index }

demande_new:
    path:     /demande/new
    defaults: { _controller: NIPAProjetBundle:Demande:addDemande }

demande_edit:
    path:     /demande/edit/{reference}
    defaults: { _controller: NIPAProjetBundle:Demande:editDemande }

demande_add_portefeuilles:
    path: demande/edit/addPortfeuilles/{reference}
    defaults: { _controller: NIPAProjetBundle:Demande:addPortefeuilles }

demande_delete_portefeuilles:
    path: demande/edit/{referenceDemande}/deletePortefeuilles/{referencePortefeuille}
    defaults: { _controller: NIPAProjetBundle:Demande:deletePortefeuilles }

demande_update_budget:
    path: demande/edit/{reference}/budget/update
    defaults: { _controller: NIPAProjetBundle:Demande:editBudget }