<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeBudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
