<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
