<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeDiversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDiversRepository extends \Doctrine\ORM\EntityRepository
{
}
