<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeDirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDirectionRepository extends \Doctrine\ORM\EntityRepository
{
}
