<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeOffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeOffresRepository extends \Doctrine\ORM\EntityRepository
{
}
