<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeTypeProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeTypeProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
