<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
