<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeStatutInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeStatutInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
