<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeInterlocuteurMOARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeInterlocuteurMOARepository extends \Doctrine\ORM\EntityRepository
{
}
