<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandePorteurMetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePorteurMetierRepository extends \Doctrine\ORM\EntityRepository
{
}
