<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeSDMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeSDMRepository extends \Doctrine\ORM\EntityRepository
{
}
