<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeListeInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeListeInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
