<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeEntiteMetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEntiteMetierRepository extends \Doctrine\ORM\EntityRepository
{
}
