<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandePrioriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePrioriteRepository extends \Doctrine\ORM\EntityRepository
{
}
