<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * DemandeSaveFiltresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeSaveFiltresRepository extends \Doctrine\ORM\EntityRepository
{
}
