<?php

namespace NIPA\ProjetBundle\Entity;

/**
 * PortefeuilleEnveloppeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleEnveloppeRepository extends \Doctrine\ORM\EntityRepository
{
}
