<?php

namespace NIPA\ProjetBundle\Entity;

/**
 * portfeuilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class portfeuilleRepository extends \Doctrine\ORM\EntityRepository
{
}
