<?php

namespace NIPA\ProjetBundle\Entity;

/**
 * PortefeuilleAnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleAnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
