<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * PortefeuilleEnveloppeConsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleEnveloppeConsRepository extends \Doctrine\ORM\EntityRepository
{
}
