<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * portfeuilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleRepository extends \Doctrine\ORM\EntityRepository
{
}
