<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * PortefeuilleStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
