<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * PortefeuilleEnveloppePrevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortefeuilleEnveloppePrevRepository extends \Doctrine\ORM\EntityRepository
{
}
