<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
