<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetBudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
