<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetJalonDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetJalonDateRepository extends \Doctrine\ORM\EntityRepository
{
}
