<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeJalonDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeJalonDateRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getJalonDateProjetEnCadrage($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeJalonDate a JOIN a.jalonDate l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Cadrage");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }    
    
    public function getJalonDateProjetEnConception($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeJalonDate a JOIN a.jalonDate l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Conception");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }  
    
    public function getJalonDateProjetEnRealisation($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeJalonDate a JOIN a.jalonDate l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Réalisation");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }      
 
    public function getJalonDateProjetALL($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeJalonDate a JOIN a.jalonDate l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet');
        $query->setParameter('projet', $projet);

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }       
    
}
