<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
