<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
