<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeStepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeStepsRepository extends \Doctrine\ORM\EntityRepository
{
}
