<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeLivrableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeLivrableRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getLivrableProjetEnCadrage($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeLivrable a JOIN a.livrable l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Cadrage");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }    
    
    public function getLivrableProjetEnConception($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeLivrable a JOIN a.livrable l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Conception");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }  
    
    public function getLivrableProjetEnRealisation($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeLivrable a JOIN a.livrable l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet AND e.nom = :etape');
        $query->setParameter('projet', $projet);
        $query->setParameter('etape', "En Réalisation");

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    } 
    
    public function getLivrableProjetALL($projet)
    {
        $query = $this->_em->createQuery('SELECT a FROM NIPAProjetBundle:ProjetListeLivrable a JOIN a.livrable l JOIN l.refPhase r JOIN r.refEtape e WHERE a.projet = :projet');
        $query->setParameter('projet', $projet);

        // Utilisation de getSingleResult SI ON retourne qu'un seul résultat
        return $query->getResult();
    }      
    
}
