<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetLivrableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetLivrableRepository extends \Doctrine\ORM\EntityRepository
{
}
