<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeJalonDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeJalonDateRepository extends \Doctrine\ORM\EntityRepository
{
}
