<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetListeLivrableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetListeLivrableRepository extends \Doctrine\ORM\EntityRepository
{
}
