<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetPhaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetPhaseRepository extends \Doctrine\ORM\EntityRepository
{
}
