<?php

namespace NIPA\ProjetBundle\Repository;

/**
 * ProjetByPassPhaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetByPassPhaseRepository extends \Doctrine\ORM\EntityRepository
{
}
